# Generated by Django 2.2 on 2020-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienthistory',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
