# Generated by Django 2.2 on 2020-09-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20200905_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='patient',
        ),
    ]
